config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users

  resources :accounts

  # Free Sidekiq
  if Gem.loaded_specs.key? 'sidekiq'
    require 'sidekiq'
    require 'sidekiq/web'
  end

  # Sidekiq Pro
  # if Gem.loaded_specs.key? 'sidekiq-pro'
  #   require 'sidekiq-pro'
  #   require 'sidekiq/pro/web'
  # end

  # Only admins can see the Sidekiq Dashboard
  authenticate :user, ->(u) { u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :contact_requests, path: 'contact-requests', only: [:index]
  get 'contact-us', to: 'contact_requests#new', as: 'contact_us'
  post 'contact-us', to: 'contact_requests#create'

  # Public Controller
  get 'cookie-policy', to: 'public#cookie_policy'
  get 'faq', to: 'public#faq'
  get 'privacy-policy-california', to: 'public#privacy_policy_california'
  get 'privacy-policy', to: 'public#privacy_policy'
  get 'terms-of-use', to: 'public#terms_of_use'
  post 'saw_cookie_notice', to: 'public#saw_cookie_notice'

  # Default root path
  root to: 'public#index'

  match '*path', via: :all, to: 'public#not_found'
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if flash_message_is_cookie_info(msg) %>
    <div class="alert alert-info alert-dismissible fade show mb-4" role="alert">
      <%= msg %>
      <%= button_to '', saw_cookie_notice_path, method: :post, class: "btn-close", "data-bs-dismiss": "alert", "aria-label": "Close" %>
    </div>
  <% else %>
    <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissible fade show mb-4" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer bg-light text-muted">
  <!-- Navigation  -->
  <section class="footer-navigation">
    <div class="container">
      <div class="row py-4">
        <div class="col-md-12 col-xl-3 mb-4 mb-md-5 mb-xl-0">
          <div class="text-uppercase fw-bold mb-3"><%= COMPANY_NAME %></div>
          <p>
            This is company description.
          </p>
          <a href="<%= root_path %>">
            <%= image_tag 'logo.png', alt: t('assets.logo'), title: t('assets.logo'), class: 'footer-brand', width: "70" %>
          </a>
        </div>

        <div class="col-md-3 col-xl-3 mb-4 mb-lg-0">
          <div class="text-uppercase fw-bold mb-3">Company</div>
          <ul class="nav flex-column">
            <li class="nav-item">
              <%= link_to t('footer.nav_links.faq'), faq_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to t('footer.nav_links.contact_us'), contact_us_path, class: 'nav-link' %>
            </li>
            <% if user_signed_in? && current_user.is_admin? %>
              <li class="nav-item">
                <%= link_to t('footer.nav_links.contact_requests'), contact_requests_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="col-md-3 col-xl-3 mb-4 mb-lg-0">
          <div class="text-uppercase fw-bold mb-3">Conditions</div>
          <ul class="nav flex-column">
            <li class="nav-item">
              <%= link_to t('footer.nav_links.terms_of_use'), terms_of_use_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to t('footer.nav_links.privacy_policy'), privacy_policy_path, class: 'nav-link' %>
            <li class="nav-item">
              <%= link_to t('footer.nav_links.opt_out'), new_opt_out_request_path, class: 'nav-link' %>
            </li>
            <% if user_signed_in? && current_user.is_admin? %>
              <li class="nav-item">
                <%= link_to t('footer.nav_links.opt_out_requests'), opt_out_requests_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="col-md col-xl">
          <div class="text-uppercase fw-bold mb-3">Contact</div>
          <p>
            <i class="fa-solid fa-house me-3"></i><%= OUR_STREET_ADDRESS %><br />
            <span style="padding-left: 2.1rem;"><%= OUR_CITY_STATE_ZIP %></span>
          </p>
          <p>
            <i class="fa-solid fa-envelope me-3"></i><%= OUR_EMAIL_ADDRESS %>
          </p>
          <p>
            <i class="fa-solid fa-phone me-3"></i><%= OUR_TELEPHONE %>
          </p>
        </div>
      </div>
    </div>
  </section>

  <!-- Copyright -->
  <div class="footer-copyright text-center p-3">
    <small>&copy; <%= Date.today.year %>  <%= COMPANY_LLC %></small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a href="<%= root_path %>" class="navbar-brand">
        <%= image_tag 'logo.png', alt: t('assets.logo'), title: t('assets.logo'), width: "130" %>
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to edit_user_registration_path, class: "nav-link" do %>
                Edit Account
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                Sign Out
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link" do %>
                Sign In
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "nav-link" do %>
                Sign Up
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('site_title') %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <main class='container py-5'>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
            integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
            crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/error_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('site_title') %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>