config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users

  resources :accounts

  # Free Sidekiq
  if Gem.loaded_specs.key? 'sidekiq'
    require 'sidekiq'
    require 'sidekiq/web'
  end

  # Sidekiq Pro
  # if Gem.loaded_specs.key? 'sidekiq-pro'
  #   require 'sidekiq-pro'
  #   require 'sidekiq/pro/web'
  # end

  # Only admins can see the Sidekiq Dashboard
  authenticate :user, ->(u) { u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :contact_requests, path: 'contact-requests', only: [:index]
  get 'contact-us', to: 'contact_requests#new', as: 'contact_us'
  post 'contact-us', to: 'contact_requests#create'

  # Public Controller
  get 'cookie-policy', to: 'public#cookie_policy'
  get 'faq', to: 'public#faq'
  get 'privacy-policy-california', to: 'public#privacy_policy_california'
  get 'privacy-policy', to: 'public#privacy_policy'
  get 'terms-of-use', to: 'public#terms_of_use'
  post 'saw_cookie_notice', to: 'public#saw_cookie_notice'

  # Default root path
  root to: 'public#index'

  match '*path', via: :all, to: 'public#not_found'
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id                     :bigint           not null, primary key
#  billing_address        :string(255)
#  billing_city           :string(255)
#  billing_country_code   :string(255)      default("US")
#  billing_state          :string(255)
#  is_active              :boolean          default(FALSE)
#  name                   :string(255)
#  telephone              :string(255)
#  telephone_country_code :string(255)      default("1")
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class Account < ApplicationRecord
  validates_presence_of :name,
                        :billing_address,
                        :billing_city,
                        :billing_state
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def create
    @account = Account.new(accounts_params)

    if @account.save

    else

    end
  end

  def update
  end

  private

  def accounts_params
    params.require(:account)
      .permit(
        :name,
        :billing_address,
        :billing_city,
        :billing_state,
        :billing_country_code,
        :telephone_country_code,
        :telephone
      )
  end
end

app/views/accounts/_form.html.erb
<%= form_for(account, url: accounts_path(account)) do |f| %>

  <%= render "devise/shared/error_messages", resource: account %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :billing_address %>
    <%= f.text_field :billing_address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :billing_city %>
    <%= f.text_field :billing_city, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :billing_state %>
    <%= f.text_field :billing_state, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :billing_country_code %>
    <%= f.text_field :billing_country_code, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :telephone_country_code %>
    <%= f.text_field :telephone_country_code, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :telephone %>
    <%= f.text_field :telephone, class: 'form-control' %>
  </div>

  <div class="form-group mb-5">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>